Je 56113
jelastic-jps/lets-encrypt pull request #261
Opened 2023-08-02 14:31 UTC by lazarenkoalexey

2023-08-09 12:35 UTC, SlavaKatiukha requested changes

2023-08-09 12:35 UTC, SlavaKatiukha commented on manifest.jps
> +      var j = jelastic, resp = j.dev.scripting.Eval(appidValue, session, '${env.envName}-${targetNodes.nodeGroup}-${globals.scriptSufix}', {action:'${this.action}'});
```suggestion
      var resp = api.dev.scripting.Eval(appidValue, session, '${env.envName}-${targetNodes.nodeGroup}-${globals.scriptSufix}', {action:'${this.action}'});
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on manifest.jps
> +      var appidValue = api.dev.apps.CreatePersistence ? "${globals.envAppid}" : appid;
```suggestion
      var targetAppid = api.dev.apps.CreatePersistence ? "${globals.envAppid}" : appid;
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on manifest.jps
> +      jelastic.dev.scripting.DeleteScript(appidValue, session, '${env.envName}-${targetNodes.nodeGroup}-${globals.scriptSufix}');
```suggestion
      api.dev.scripting.DeleteScript(targetAppid, session, '${env.envName}-${targetNodes.nodeGroup}-${globals.scriptSufix}');
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on manifest.jps
> +      var appidValue = api.dev.apps.CreatePersistence ? "${globals.envAppid}" : appid;
```suggestion
      var targetAppid = api.dev.apps.CreatePersistence ? "${globals.envAppid}" : appid;
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on manifest.jps
> +      return jelastic.dev.scripting.CreateScript(appidValue, session, "${this.scriptName}", "js", "${this.code:}")
```suggestion
      return api.dev.scripting.CreateScript(targetAppid, session, "${this.scriptName}", "js", "${this.code:}")
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on scripts/ssl-manager.js
> +        scriptsAppid = "",
```suggestion
        targetAppid,
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on scripts/ssl-manager.js
> +    scriptsAppid = api.dev.apps.CreatePersistence ? config.envAppid : appid;
```suggestion
    targetAppid = api.dev.apps.CreatePersistence ? config.envAppid : appid;
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on scripts/ssl-manager.js
> +        return api.dev.scripting.CreateScript(scriptsAppid, session, config.scriptName, "js", sCode);
```suggestion
        return api.dev.scripting.CreateScript(targetAppid, session, config.scriptName, "js", sCode);
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on scripts/ssl-manager.js
> +                api.dev.scripting.DeleteScript(scriptsAppid, session, scriptingScriptName);
```suggestion
                api.dev.scripting.DeleteScript(targetAppid, session, scriptingScriptName);
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on scripts/ssl-manager.js
> +        return api.dev.scripting.CreateScript(scriptsAppid, session, config.scriptName, "js", sCode);
```suggestion
        return api.dev.scripting.CreateScript(targetAppid, session, config.scriptName, "js", sCode);
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on scripts/ssl-manager.js
> +                api.dev.scripting.DeleteScript(scriptsAppid, session, scriptingScriptName);
```suggestion
                api.dev.scripting.DeleteScript(targetAppid, session, scriptingScriptName);
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on scripts/ssl-manager.js
> +            resp = api.dev.scripting.CreateScript(scriptsAppid, session, scriptingScriptName, "js", scriptBody);
```suggestion
            resp = api.dev.scripting.CreateScript(targetAppid, session, scriptingScriptName, "js", scriptBody);
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on scripts/ssl-manager.js
> +        var resp = jelastic.dev.scripting.Eval(scriptsAppid, session, config.scriptName, params);
```suggestion
        var resp = api.dev.scripting.Eval(targetAppid, session, config.scriptName, params);
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on scripts/ssl-manager.js
> +        return api.dev.scripting.GetScript(scriptsAppid, session, name);
```suggestion
        return api.dev.scripting.GetScript(targetAppid, session, name);
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on scripts/ssl-manager.js
>          if (jelastic.marketplace && jelastic.marketplace.console && message) {
```suggestion
        if (api.marketplace && api.marketplace.console && message) {
```

2023-08-09 12:35 UTC, SlavaKatiukha commented on scripts/ssl-manager.js
> +            return jelastic.marketplace.console.WriteLog(message);
```suggestion
            return api.marketplace.console.WriteLog(message);
```

2023-08-29 11:15 UTC, SlavaKatiukha commented on manifest.jps
> +baseUrl: https://raw.githubusercontent.com/jelastic-jps/lets-encrypt/JE-56113
don't forget to change after testing

2023-08-29 11:16 UTC, SlavaKatiukha requested changes

2023-08-29 11:16 UTC, SlavaKatiukha commented on manifest.jps
> +      var resp = api.dev.scripting.Eval(appidValue, session, '${env.envName}-${targetNodes.nodeGroup}-${globals.scriptSufix}', {action:'${this.action}'});
appidValue?

2023-08-29 11:20 UTC, lazarenkoalexey commented on manifest.jps
> +      var resp = api.dev.scripting.Eval(appidValue, session, '${env.envName}-${targetNodes.nodeGroup}-${globals.scriptSufix}', {action:'${this.action}'});
fixed

2023-08-29 11:21 UTC, SlavaKatiukha approved these changes

2023-08-29 11:25 UTC, SlavaKatiukha approved these changes

2023-11-17 15:53 UTC, merged